/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.smc.calendar.caldav.schedule.contact.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.smc.calendar.caldav.schedule.contact.model.ScheduleContact;
import it.smc.calendar.caldav.schedule.contact.service.ScheduleContactLocalService;
import it.smc.calendar.caldav.schedule.contact.service.persistence.ScheduleContactPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the schedule contact local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.smc.calendar.caldav.schedule.contact.service.impl.ScheduleContactLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.smc.calendar.caldav.schedule.contact.service.impl.ScheduleContactLocalServiceImpl
 * @generated
 */
public abstract class ScheduleContactLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   ScheduleContactLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ScheduleContactLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.smc.calendar.caldav.schedule.contact.service.ScheduleContactLocalServiceUtil</code>.
	 */

	/**
	 * Adds the schedule contact to the database. Also notifies the appropriate model listeners.
	 *
	 * @param scheduleContact the schedule contact
	 * @return the schedule contact that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ScheduleContact addScheduleContact(ScheduleContact scheduleContact) {
		scheduleContact.setNew(true);

		return scheduleContactPersistence.update(scheduleContact);
	}

	/**
	 * Creates a new schedule contact with the primary key. Does not add the schedule contact to the database.
	 *
	 * @param scheduleContactId the primary key for the new schedule contact
	 * @return the new schedule contact
	 */
	@Override
	@Transactional(enabled = false)
	public ScheduleContact createScheduleContact(long scheduleContactId) {
		return scheduleContactPersistence.create(scheduleContactId);
	}

	/**
	 * Deletes the schedule contact with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param scheduleContactId the primary key of the schedule contact
	 * @return the schedule contact that was removed
	 * @throws PortalException if a schedule contact with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ScheduleContact deleteScheduleContact(long scheduleContactId)
		throws PortalException {

		return scheduleContactPersistence.remove(scheduleContactId);
	}

	/**
	 * Deletes the schedule contact from the database. Also notifies the appropriate model listeners.
	 *
	 * @param scheduleContact the schedule contact
	 * @return the schedule contact that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ScheduleContact deleteScheduleContact(
		ScheduleContact scheduleContact) {

		return scheduleContactPersistence.remove(scheduleContact);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ScheduleContact.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return scheduleContactPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.smc.calendar.caldav.schedule.contact.model.impl.ScheduleContactModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return scheduleContactPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.smc.calendar.caldav.schedule.contact.model.impl.ScheduleContactModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return scheduleContactPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return scheduleContactPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return scheduleContactPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ScheduleContact fetchScheduleContact(long scheduleContactId) {
		return scheduleContactPersistence.fetchByPrimaryKey(scheduleContactId);
	}

	/**
	 * Returns the schedule contact matching the UUID and group.
	 *
	 * @param uuid the schedule contact's UUID
	 * @param groupId the primary key of the group
	 * @return the matching schedule contact, or <code>null</code> if a matching schedule contact could not be found
	 */
	@Override
	public ScheduleContact fetchScheduleContactByUuidAndGroupId(
		String uuid, long groupId) {

		return scheduleContactPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the schedule contact with the primary key.
	 *
	 * @param scheduleContactId the primary key of the schedule contact
	 * @return the schedule contact
	 * @throws PortalException if a schedule contact with the primary key could not be found
	 */
	@Override
	public ScheduleContact getScheduleContact(long scheduleContactId)
		throws PortalException {

		return scheduleContactPersistence.findByPrimaryKey(scheduleContactId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(scheduleContactLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ScheduleContact.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("scheduleContactId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			scheduleContactLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ScheduleContact.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"scheduleContactId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(scheduleContactLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ScheduleContact.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("scheduleContactId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<ScheduleContact>() {

				@Override
				public void performAction(ScheduleContact scheduleContact)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, scheduleContact);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(ScheduleContact.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return scheduleContactLocalService.deleteScheduleContact(
			(ScheduleContact)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return scheduleContactPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the schedule contacts matching the UUID and company.
	 *
	 * @param uuid the UUID of the schedule contacts
	 * @param companyId the primary key of the company
	 * @return the matching schedule contacts, or an empty list if no matches were found
	 */
	@Override
	public List<ScheduleContact> getScheduleContactsByUuidAndCompanyId(
		String uuid, long companyId) {

		return scheduleContactPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of schedule contacts matching the UUID and company.
	 *
	 * @param uuid the UUID of the schedule contacts
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of schedule contacts
	 * @param end the upper bound of the range of schedule contacts (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching schedule contacts, or an empty list if no matches were found
	 */
	@Override
	public List<ScheduleContact> getScheduleContactsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ScheduleContact> orderByComparator) {

		return scheduleContactPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the schedule contact matching the UUID and group.
	 *
	 * @param uuid the schedule contact's UUID
	 * @param groupId the primary key of the group
	 * @return the matching schedule contact
	 * @throws PortalException if a matching schedule contact could not be found
	 */
	@Override
	public ScheduleContact getScheduleContactByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return scheduleContactPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the schedule contacts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.smc.calendar.caldav.schedule.contact.model.impl.ScheduleContactModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of schedule contacts
	 * @param end the upper bound of the range of schedule contacts (not inclusive)
	 * @return the range of schedule contacts
	 */
	@Override
	public List<ScheduleContact> getScheduleContacts(int start, int end) {
		return scheduleContactPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of schedule contacts.
	 *
	 * @return the number of schedule contacts
	 */
	@Override
	public int getScheduleContactsCount() {
		return scheduleContactPersistence.countAll();
	}

	/**
	 * Updates the schedule contact in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param scheduleContact the schedule contact
	 * @return the schedule contact that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ScheduleContact updateScheduleContact(
		ScheduleContact scheduleContact) {

		return scheduleContactPersistence.update(scheduleContact);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ScheduleContactLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		scheduleContactLocalService = (ScheduleContactLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ScheduleContactLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ScheduleContact.class;
	}

	protected String getModelClassName() {
		return ScheduleContact.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = scheduleContactPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected ScheduleContactLocalService scheduleContactLocalService;

	@Reference
	protected ScheduleContactPersistence scheduleContactPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}