/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.smc.calendar.caldav.schedule.contact.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import it.smc.calendar.caldav.schedule.contact.model.ScheduleContact;
import it.smc.calendar.caldav.schedule.contact.model.ScheduleContactModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ScheduleContact service. Represents a row in the &quot;CalDAVSync_ScheduleContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ScheduleContactModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScheduleContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScheduleContactImpl
 * @generated
 */
public class ScheduleContactModelImpl
	extends BaseModelImpl<ScheduleContact> implements ScheduleContactModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a schedule contact model instance should use the <code>ScheduleContact</code> interface instead.
	 */
	public static final String TABLE_NAME = "CalDAVSync_ScheduleContact";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"scheduleContactId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"commonName", Types.VARCHAR}, {"emailAddress", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scheduleContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commonName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CalDAVSync_ScheduleContact (uuid_ VARCHAR(75) null,scheduleContactId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commonName VARCHAR(75) null,emailAddress VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CalDAVSync_ScheduleContact";

	public static final String ORDER_BY_JPQL =
		" ORDER BY scheduleContact.commonName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CalDAVSync_ScheduleContact.commonName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EMAILADDRESS_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long COMMONNAME_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ScheduleContactModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scheduleContactId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScheduleContactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scheduleContactId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScheduleContact.class;
	}

	@Override
	public String getModelClassName() {
		return ScheduleContact.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ScheduleContact, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ScheduleContact, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScheduleContact, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ScheduleContact)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ScheduleContact, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ScheduleContact, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ScheduleContact)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ScheduleContact, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ScheduleContact, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ScheduleContact>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ScheduleContact.class.getClassLoader(), ScheduleContact.class,
			ModelWrapper.class);

		try {
			Constructor<ScheduleContact> constructor =
				(Constructor<ScheduleContact>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ScheduleContact, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ScheduleContact, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ScheduleContact, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ScheduleContact, Object>>();
		Map<String, BiConsumer<ScheduleContact, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ScheduleContact, ?>>();

		attributeGetterFunctions.put("uuid", ScheduleContact::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ScheduleContact, String>)ScheduleContact::setUuid);
		attributeGetterFunctions.put(
			"scheduleContactId", ScheduleContact::getScheduleContactId);
		attributeSetterBiConsumers.put(
			"scheduleContactId",
			(BiConsumer<ScheduleContact, Long>)
				ScheduleContact::setScheduleContactId);
		attributeGetterFunctions.put("groupId", ScheduleContact::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ScheduleContact, Long>)ScheduleContact::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ScheduleContact::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ScheduleContact, Long>)ScheduleContact::setCompanyId);
		attributeGetterFunctions.put("userId", ScheduleContact::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ScheduleContact, Long>)ScheduleContact::setUserId);
		attributeGetterFunctions.put("userName", ScheduleContact::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ScheduleContact, String>)ScheduleContact::setUserName);
		attributeGetterFunctions.put(
			"createDate", ScheduleContact::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ScheduleContact, Date>)ScheduleContact::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ScheduleContact::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ScheduleContact, Date>)
				ScheduleContact::setModifiedDate);
		attributeGetterFunctions.put(
			"commonName", ScheduleContact::getCommonName);
		attributeSetterBiConsumers.put(
			"commonName",
			(BiConsumer<ScheduleContact, String>)
				ScheduleContact::setCommonName);
		attributeGetterFunctions.put(
			"emailAddress", ScheduleContact::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<ScheduleContact, String>)
				ScheduleContact::setEmailAddress);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getScheduleContactId() {
		return _scheduleContactId;
	}

	@Override
	public void setScheduleContactId(long scheduleContactId) {
		_scheduleContactId = scheduleContactId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getCommonName() {
		if (_commonName == null) {
			return "";
		}
		else {
			return _commonName;
		}
	}

	@Override
	public void setCommonName(String commonName) {
		_columnBitmask = -1L;

		_commonName = commonName;
	}

	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		_columnBitmask |= EMAILADDRESS_COLUMN_BITMASK;

		if (_originalEmailAddress == null) {
			_originalEmailAddress = _emailAddress;
		}

		_emailAddress = emailAddress;
	}

	public String getOriginalEmailAddress() {
		return GetterUtil.getString(_originalEmailAddress);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ScheduleContact.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ScheduleContact.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ScheduleContact toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ScheduleContact>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScheduleContactImpl scheduleContactImpl = new ScheduleContactImpl();

		scheduleContactImpl.setUuid(getUuid());
		scheduleContactImpl.setScheduleContactId(getScheduleContactId());
		scheduleContactImpl.setGroupId(getGroupId());
		scheduleContactImpl.setCompanyId(getCompanyId());
		scheduleContactImpl.setUserId(getUserId());
		scheduleContactImpl.setUserName(getUserName());
		scheduleContactImpl.setCreateDate(getCreateDate());
		scheduleContactImpl.setModifiedDate(getModifiedDate());
		scheduleContactImpl.setCommonName(getCommonName());
		scheduleContactImpl.setEmailAddress(getEmailAddress());

		scheduleContactImpl.resetOriginalValues();

		return scheduleContactImpl;
	}

	@Override
	public int compareTo(ScheduleContact scheduleContact) {
		int value = 0;

		value = getCommonName().compareTo(scheduleContact.getCommonName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ScheduleContact)) {
			return false;
		}

		ScheduleContact scheduleContact = (ScheduleContact)obj;

		long primaryKey = scheduleContact.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ScheduleContactModelImpl scheduleContactModelImpl = this;

		scheduleContactModelImpl._originalUuid = scheduleContactModelImpl._uuid;

		scheduleContactModelImpl._originalGroupId =
			scheduleContactModelImpl._groupId;

		scheduleContactModelImpl._setOriginalGroupId = false;

		scheduleContactModelImpl._originalCompanyId =
			scheduleContactModelImpl._companyId;

		scheduleContactModelImpl._setOriginalCompanyId = false;

		scheduleContactModelImpl._setModifiedDate = false;

		scheduleContactModelImpl._originalEmailAddress =
			scheduleContactModelImpl._emailAddress;

		scheduleContactModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ScheduleContact> toCacheModel() {
		ScheduleContactCacheModel scheduleContactCacheModel =
			new ScheduleContactCacheModel();

		scheduleContactCacheModel.uuid = getUuid();

		String uuid = scheduleContactCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			scheduleContactCacheModel.uuid = null;
		}

		scheduleContactCacheModel.scheduleContactId = getScheduleContactId();

		scheduleContactCacheModel.groupId = getGroupId();

		scheduleContactCacheModel.companyId = getCompanyId();

		scheduleContactCacheModel.userId = getUserId();

		scheduleContactCacheModel.userName = getUserName();

		String userName = scheduleContactCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			scheduleContactCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			scheduleContactCacheModel.createDate = createDate.getTime();
		}
		else {
			scheduleContactCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			scheduleContactCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			scheduleContactCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		scheduleContactCacheModel.commonName = getCommonName();

		String commonName = scheduleContactCacheModel.commonName;

		if ((commonName != null) && (commonName.length() == 0)) {
			scheduleContactCacheModel.commonName = null;
		}

		scheduleContactCacheModel.emailAddress = getEmailAddress();

		String emailAddress = scheduleContactCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			scheduleContactCacheModel.emailAddress = null;
		}

		return scheduleContactCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ScheduleContact, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ScheduleContact, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScheduleContact, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ScheduleContact)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ScheduleContact, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ScheduleContact, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScheduleContact, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ScheduleContact)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ScheduleContact>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _scheduleContactId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _commonName;
	private String _emailAddress;
	private String _originalEmailAddress;
	private long _columnBitmask;
	private ScheduleContact _escapedModel;

}